#pragma once

#define GREEN_TXT 0x2
#define BLUE_TXT 0x1
#define WHITE_TXT 0xf
#define VGA_MEM_ADDR 0xb8000
#define KEYBOARD_MEM_ADDR 0x60 

#define DISPLAY_WIDTH 80
#define DISPLAY_HEIGHT 25
#define DISPLAY_VGA_MAX DISPLAY_HEIGHT * DISPLAY_WIDTH